### ISSUE TITLE
Update IMDSSample.py to use requests

### ISSUE THREAD

**Issue by gbowerman** [microsoft/azureimds#5]
Use requests (default with recent Python 3 versions) to simplify the existing example, 
Also, increment api-version to 2017-08-01 so it supports tags.
e.g.

#!/usr/bin/env python3
import json
import requests

endpoint = "http://169.254.169.254/metadata/instance/compute?api-version=2017-08-01"
headers={'Metadata': 'True'}
json_obj = requests.get(endpoint, headers=headers).json()

print(json.dumps(json_obj, sort_keys=True, indent=4, separators=(',', ': ')))

**Comment by LittleBoxOfSunshine** [comment]
Addressed in #6
